### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tracygardner** [raspberrypilearning/scouts-graphics#1]
- [x] Draws attention to bitmap mode. Is this what you want them to use? Might be useful to more fully explain vector mode and the difference and then let them choose. Seems reasonable at Stage 3.
- [x] Could suggest that they could choose a theme that their Scout group is interested in such as recycling or water aid. 
- [x] Rather than calling the sprites by their shape names you could give them functional names such as player, enemy, projectile; or alternatively show them how to change the names of the sprites to match their theme. 
- [x] The badge collector example is quite confusing as it would be difficult for them to create in the Scratch editor. I think it will just encourage them to import preexisting images.
- [x] 'Delete any sprites you no longer need by clicking on the (x).' Should this be about deleting any *costumes* you don't need. Some will undoubtedly create new sprites instead of new costumes so might be worth showing them how to change the code to use a new sprite?
- [x] I'd like to see a worked example of using the editor to create a simple costume. E.g. maybe you have recyclable items such as bottles or cans and recycling symbol (projectile). This will also help those young people who find it very hard to come up with an idea.

**Comment by martinohanlon** [comment]
Thanks Tracy.

Re 

> Rather than calling the sprites by their shape names you could give them functional names such as player, enemy, projectile; or alternatively show them how to change the names of the sprites to match their theme.

and 

> I'd like to see a worked example of using the editor to create a simple costume. E.g. maybe you have recyclable items such as bottles or cans and recycling symbol (projectile). This will also help those young people who find it very hard to come up with an idea.

I specifically didnt do this as I dont want to lead the participants down a particular path, as it is to fulfil a creative requirement. I'll provide a different example to the badge collector. a little more background as to the contents of the example by way of a "hint" and suggest the leader can set a theme.

**Comment by martinohanlon** [comment]
updated post feedback
